version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: weather-monitoring-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: weather_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  java_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-monitoring-java
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/weather_db
      DB_USER: myuser
      DB_PASSWORD: mypassword

volumes:
  postgres_data:
